config/routes.rb
Railspress::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users do
    get "admin" => "devise/sessions#new"
  end

  resources :posts

  get 'about' => 'pages#about'
  root 'pages#home'

end

app/models/datafile.rb
class Datafile < ActiveRecord::Base
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Bootsy::Container
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.order("created_at desc")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :bootsy_image_gallery_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<hr/>
<footer><small>Created with <%= link_to "One Month Rails", "http://www.onemonthrails.com", target: "_blank" %></small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="container">

		<!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>

		<%= link_to "Railspress", root_path, class: "navbar-brand" %>

		<!-- Place everything within .nav-collapse to hide it until above 768px -->
		<div class="nav-collapse collapse navbar-responsive-collapse">

			<ul class="nav navbar-nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About Us", about_path %></li>

				<% if user_signed_in? %>
				<li><%= link_to "New Post", new_post_path %></li>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% end %>
			</ul>

		</div><!-- /.nav-collapse -->
	</div><!-- /.container -->
</div><!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railspress</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render "layouts/header" %>

	<div class="container">

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>

		<%= yield %>

		<%= render "layouts/footer" %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, autem, nostrum vero dolorum pariatur est officiis quo dignissimos totam dicta reprehenderit ducimus saepe inventore illo ea ullam earum atque quod.</p>

app/views/pages/home.html.erb
<%= render @posts %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.bootsy_area :body, class: "form-control", rows: "12" %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-default" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <h2 class="center"><%= link_to post.title, post %></h2>
    <p><%= raw post.body %></p>

    <% if user_signed_in? %>
    	<%= link_to 'Edit', edit_post_path(post) %> |
    	<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<% if user_signed_in? %>
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
<% end %>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render @post %>